### ISSUE TITLE
A web operating system created for you! 

### ISSUE THREAD

**Issue by eaba** [polterguy/phosphorusfive#11]
Is phosphorusfive a web OS?
And what does that mean?

I want to build apps that run on IIS and Windows Services and is this possible?
Sorry am new to the world of phosphorusfive!!

**Comment by polterguy** [comment]
Quote; 

> "Phosphorus Five, also referred to as P5 in this guide, is a lot of different things. It is a simple design pattern, it is an Ajax library, it is a programming language, and it is a framework. Some would also argue that it is a web operating system. What you choose to refer to it as, is really quite irrelevant. The point is that it solves your problems, particularly the ones you’re having, as you try to create rich and interactive web apps."

Taken from its documentation; https://github.com/polterguy/phosphorusfive-dox/blob/master/README.md

Hopefully that clarifies things. If not, feel free to ask more questions. I love questions ;)

**Comment by polterguy** [comment]
> I want to build apps that run on IIS and Windows Services and is this possible?

Yup, easily!

**Comment by eaba** [comment]
Okay!
Since your doors are wide opened for questions, I will ask them in due course.
Thanks!

**Comment by polterguy** [comment]
Hehe, once you realise where the name "system42" came from, you will never be afraid of asking me a question ever again ... ;)

**Comment by eaba** [comment]
> Hehe, once you realise where the name "system42" came from, you will never be afraid of asking me a question ever again 

Hope to understand what thou meanest! ;)

**Comment by polterguy** [comment]
My favourite book; The hitchhiker's guide through the galaxy, a trilogy in 4 parts!

Google; 42 :D

https://simple.wikipedia.org/wiki/42_(answer)

**Comment by eaba** [comment]
@polterguy I have two options before me right now: 1) Just act smart and pretend everything you are saying is well understood by me. 2) Press you more for further explanations.

I read your article where you mentioned how persons said to you that phosphorusfive is an impossibility, but you stood your ground and you did; I will go for option 2!

I am in the dark!

**Comment by polterguy** [comment]
It's kind of like a joke. If you read the book, you'll understand. It's my favourite book ever. A science fiction comedy. There's even a movie made about it, which is OK, but kind of pale compared to the book itself.

The number 42 is kind of like the answer to the meaning of life, the universe, and everything. And hence becomes a funny allegory about our struggles as man :)

In a way, for me, in regards to P5, it also holds some truth to it. Since P5 and System42 are in a way opposites. Where P5 is arguably _"nothing"_, inspired by Zen philosophy, which uses an empty circle, symbolising the _"nothingness as a goal"_

In a way, P5 is this _"nothingness"_, since it's just a tiny abstraction above .Net components, allowing the user to orchestrate components together, in a very agile and flexible way. Hence its inspiration is obviously extremely inspired by Zen.

While System42 is the exact opposite, trying to be _"everything"_, and solve every possible problem.

Hence, they're in such a regard the opposites of each other ...

Don't know if that explained anything, or if it just simply created more questions. If it explained anything, I failed. If you ended up with even more questions, I succeeded ...!! :D

**[sys42.utilities.joke]**

**Comment by polterguy** [comment]
Or said with other words; [all lambda objects leads to 42](https://gaiasoul.com/2017/06/17/does-humor-belong-in-software-development/) ... ;)

**Comment by polterguy** [comment]
Sorry, I became so inspired by your question, I chose to change the [code of conduct](https://github.com/polterguy/phosphorusfive/blob/master/CODE_OF_CONDUCT.md#our-pledge), and add up my own little addendum :D

**Comment by eaba** [comment]
> Don't know if that explained anything, or if it just simply created more questions. If it explained anything, I failed. If you ended up with even more questions, I succeeded ...!! :D

You have.......but before I ask my next question, let me ponder upon all you have said...probably I might find a method that suits me!

Thanks for your time

**Comment by polterguy** [comment]
No problem, vanishing is the objective of everything. Kind of like I wrote about here; https://gaiasoul.com/2017/06/17/hyperlambda-zen-and-the-vanishing-liskov-substitution-principle/

Cheers, and keep having fun :)

**Comment by eaba** [comment]
I will like to be like you when I grow to adulthood ;)
