### ISSUE TITLE
R.A.D. IDE

### ISSUE THREAD

**Issue by polterguy** [polterguy/phosphorusfive#14]
Create a visual _"intentional based"_ programming IDE one way or another, probably only as a satellite project, entirely created in Hyperlambda, allowing users to create apps, by _"dragging and dropping"_ components into some R.A.D. IDE surface.

**Comment by iamloved** [comment]
Awesome!
It could allow more users to **play** with p5, ahh. Make it fun, for people like me, who want to create too.
And play allows real learning. Would be nice if this widened the reach for p5, increased its exististing edibility for even more people.

**Comment by polterguy** [comment]
Obviously, it wouldn't entirely replace traditional coding. But yes, I agree, it would provide an _"intentional programming"_ starting ground also for non-coders to become productive.

It would also create an eco-system for developers to sell and create components for these non-developers, which would provide value for both parties, even though it would to some extent cannibalise traditional development.

So it's a win-win for everyone the way I see it :)

**Comment by iamloved** [comment]
Of course, it can't replace coding entirely. I agree. I see it more purely as a logical and natural extension of coding.
Because one thing I see that would be great is if the RAD IDE had the ability to be transparent with the coding, and could seamlessly transition between the graphical interface and the code, organically. Such that it would be easy to step the toes into the deep water, and maybe even go for a swim, while safe to return to the shallow water without loss or struggle.
For a person like me, that is the perfect mix. Good mix of certainty and uncertainty. There will be those who will not want to transition, yet, and only look through the graphical interface. And those who will stay in the deep water (pure code) more than me. And finally those that only code purely.
I mean, if the interface layer could be such an extension as to support and be a part of the natural growth from a newbie to a programmer. That would be the ideal, as I see it.

And actually, seeing it that way, the graphical interface simply becomes a natural and logical entry way for the p5 coding as a whole.

Also, the IDE could be fully compatible with the p5 book that you wrote. Which deepens its role as a natural pathway into p5. Meaning that it would be fully possible to do the exercises in whole book using only the graphical IDE. 
But if the IDE is a seamless part of the coding, then even doing the exercises in the IDE, it would not put any restrictions on the user, because they could transition to the code and go from there, at any point, and mix and change and experiment.

I like your idea of it creating an eco-system that connects programmers at different skill level. That is the most efficient model for growth. We grow the fastest and with the most fun on the shoulders of those who came before us. That is how we are built to learn.

Great stuff :)

**Comment by polterguy** [comment]
Thx, these words echoes my own thoughts about the subject, but it's a lot of work. Don't expect it to be finished tomorrow. I have scheduled it for version 4.0 though. We're at 3.0 now ... ;)

**Comment by iamloved** [comment]
Yes, I realize it is a lot of work to achieve that quality. And it will take the time it takes. I just wanna make keep you awake, haha....

**Comment by polterguy** [comment]
Some interesting ideas about [these constructs](https://gaiasoul.com/2017/07/06/purchasing-a-function-intentional-programming/) ... :)

> Could you spare me a function bro?

**Comment by polterguy** [comment]
Partially done, read more [here](https://gaiasoul.com/2017/09/24/create-your-web-apps-in-5-minutes-seriously/)
