### ISSUE TITLE
p5.net gives a 404

### ISSUE THREAD

**Issue by leigh-pointer** [polterguy/phosphorusfive#8]
First off! Blinding good project, I <3 it!
As to my issue, 
**p5.net - HTTP REST supporting Active Events, for creating web requests**
Is this available as it give a 404 when clicked.

On another note. I would like to work and contribute an p5.Couchbase module.

**Comment by polterguy** [comment]
Thx bro :)
I have no idea what Couchbase is, but if it adds value, and is of general interest to lots of others, I will probably love it!! :)

As to your 404, this **might** be due to using wrong protocol (http versus https). You can check out an example of how to use it in the sys42.translate.hl file, which does a Google Translate lookup ...

Try it towards a different end point, if it still doesn't work, hit me with a re-producible, and I'll take a deeper dive :)

PS!
Feel free to close this yourself, if it fixes your problem ...

**Comment by leigh-pointer** [comment]
**What is Couchbase ?** 
Couchbase Server is a NoSQL database, which has become the de facto standard for building Systems of Engagement. It is designed with a distributed architecture for performance, scalability, and availability. It enables developers to build applications easier and faster by leveraging the power of SQL with the flexibility of JSON.

[https://www.couchbase.com/](url) 

The protocol didn't grab it so I will dive in to sys42.translate.hl.  Thanks.
Regards.

**Comment by polterguy** [comment]
Awesome!

I once started work on MongoDB, but stopped due to not agreeing with myself about how to implement it. There's in fact an existing (but very immature) project skeleton for MongoDB in the source. It's not included in the solution though. Couchbase sounds like something users probably definitely would want, I would assume :)

I've started work on MySQL myself, and will probably make it a part of the next release, for the record. This is easier though I feel, than doing "full Mongo support", since it relies upon SQL directly, and simply being able to create a connection, passing in some SQL to it, through a MySQLCommand ...

Love it, go for it :)

Let me know how your 404 problem goes ... :)

In theory, p5.http.get:"http://someurl.com" - **Should** work ...

PS, make sure you wrap the URL in double quotes, since otherwise the Hyperlambda parser will assume its "type declaration" is "http" - Colon separates the name, value, and (optionally) the "type declaration. To for instance declare an integer, is done like the following ...

```
_foo:int:5
```

**Comment by polterguy** [comment]
Example;

```
p5.http.get:"https://google.com"
```

Which for me yields.

```
p5.http.get
  result:"https://google.com/"
    status:OK
    Status-Description:OK
    Content-Type:text/html; charset=ISO-8859-1
    Last-Modified:date:"2017-03-11T01:33:12.335"
    Response-Uri:"https://www.google.com.cy/?gfe_rd=cr&ei=tzfDWJC7KdKs8we47rDgDQ"
    Server:gws
    Date:"Fri, 10 Mar 2017 23:33:12 GMT"
    Expires:-1
    Cache-Control:private, max-age=0
    P3P:@"CP=""This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."""
    X-XSS-Protection:1; mode=block
    X-Frame-Options:SAMEORIGIN
    Set-Cookie:"NID=98=Q0idFuoLvLIjiIVV7H_SlyPz2ui6EhSlcRyS7CGuVwtijJteS2L-miw0LgWR2_a4NT9-rxGuTnLeFVldG7HX5PD66g5Y4GkUmLPHcCLrGshSpKoAIsTJO2rA8W-F6g0d; expires=Sat, 09-Sep-2017 23:33:12 GMT; path=/; domain=.google.com.cy; HttpOnly"
    Alt-Svc:@"quic="":443""; ma=2592000; v=""36,35,34"""
    Accept-Ranges:none
    Vary:Accept-Encoding
    Transfer-Encoding:chunked
    content:@"... tons of HTML ..."
```

The to retrieve the HTML (using lambda expressions), passing it into another event, would resemble something like the following.

```
p5.http.get:"https://google.com"
some.active.event.needing.the.html:x:/@p5.http.get/*/content?value
```

Notice, I am assuming you're using Hyperlambda. If you're in C#, it would look something like the following.

```csharp
var node = new Node ();
node.Value = "https://google.com";
/* optionally
node.Name = "p5.http.get";
context.RaiseEvent ("p5.http.get", node);
```

**Comment by leigh-pointer** [comment]
404 is not sorted so I went back through the releases and found a BETA package with the **p5.net** in it **phosphorusfive-1.0-BETA17** I have grabbed myself that and started sorting out the issues in the project.  I would appreciate the p5.net project that you are working as it would save me some time.

I will look at your implementation of MongoDB and see if I can pick it up.  

Thanks for the tips ;)

**Comment by polterguy** [comment]
Darn it, I'll reopen the issue, until it's fixed ...

**Comment by leigh-pointer** [comment]
Thanks ;)

**Comment by polterguy** [comment]
So, any luck on this ...?

PS!
I got it to work with the last release, using p5.http.get ...

**Comment by polterguy** [comment]
I'm going to close this, since I can't reproduce it ...

**Comment by leigh-pointer** [comment]
I think you are missing the issue.  My issue is not with the code as (What my problem is) I cant download p5.net from GitHub the link returns a 404 error.

**Comment by polterguy** [comment]
Ahhhh ...
Get it, sorry Leigh :)

p5.net has been renamed, and was an old library, which is now converted into p5.http.

p5.http contains most of the stuff from p5.net, such as these Active Events;

* p5.http.get - HTTP verb
* p5.http.post - HTTP verb
* p5.http.put - HTTP verb
* p5.http.delete - HTTP verb

In addition it contains these Active Events

* p5.http.post-file
* p5.http.put-file

That posts/puts files to an endpoint (crucially **without** loading them into memory), in addition to.

* p5.http.get-file - Loads file, and saves it directly to disc (**without** loading it into memory)

In addition to three "native" events, only possible to invoke from C#.

* .p5.http.get-native
* .p5.http.post-native
* .p5.http.put-native

The latter events, can only be raised through C# (due to starting with a ".")

At some point, I was meddling with MimeKit, and had a couple of additional events. Unfortunately, I couldn't "agree" with myself, in regards to the "API", and removed them from the core (temporarily, until I start "agreeing" with myself) - And the project (p5.net) contained some helper events to PGP encrypt/create MIME messages, etc - But this is not there anymore ...

Does it ask you for "p5.net" somewhere ...?

It shouldn't!!

p5.net is *gone* and should be ...

**Comment by leigh-pointer** [comment]
I see no refs to p5.net only I think it might be an idea to update the documentation and remove p5.net polterguy/phosphorusfive/edit/master/plugins/extras/README.md 

On another point. Have you thought about moving your docx over to the wiki ?

**Comment by polterguy** [comment]
Darn it, didn't even realise. It's a pretty **massive** project, and sometimes difficult for me to hold all of its threads alone. Which I have been doing, for (actually, belive me when I say this) - **10 years** ...!! :P

Thx, will update dox. Leaving this one open until I have ...

(Unless you'd like to pass me a patch for its dox ... :)

**Comment by polterguy** [comment]
PS!
The "book" is my current preferred documentation now (although incomplete, still valuable I think)

https://github.com/polterguy/phosphorusfive-dox

**Comment by polterguy** [comment]
For the record, I am working on this, though to be a part of _"the guide"_, where I will put all dox, also the reference parts, which will be in appendixes. Which you can find [here](https://github.com/polterguy/phosphorusfive-dox)

I still haven't finished up the _"core"_ parts though, I've got to do branching dox, at which point I will start working on the _"reference parts"_, where p5.http probably will have its own chapter, in addition to all other parts ...

Wiki is a good idea for more community contributions I think, and probably a good idea, but I think _"the guide"_ still needs to be written :)

**Comment by polterguy** [comment]
Fixed, all the documentation should now be up to date. Notice, I still haven't created a release wrapping everything that is now documented. Let me know if you find more "dead links" or similar problems.
